// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJmo2tdG6kQGZ4iwYBrjeU
// Component: 6Seh2opbHxlH6n
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: bJmo2tdG6kQGZ4iwYBrjeU/projectcss
import sty from "./PlasmicRatings.module.css"; // plasmic-import: 6Seh2opbHxlH6n/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: mrZsWSIlSFwSc7/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootstars_five]: hasVariant(variants, "stars", "five"),
          [sty.rootstars_four]: hasVariant(variants, "stars", "four"),
          [sty.rootstars_one]: hasVariant(variants, "stars", "one"),
          [sty.rootstars_three]: hasVariant(variants, "stars", "three"),
          [sty.rootstars_two]: hasVariant(variants, "stars", "two"),
          [sty.rootstars_zero]: hasVariant(variants, "stars", "zero")
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__kmRga, {
              [sty.svgstars_five__kmRgao4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_zero__kmRgamCmim]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__nuAhu, {
              [sty.svgstars_five__nuAhuo4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__nuAhUaWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__nuAhUoy01K]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__nuAhugjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__nuAhUcGaiC]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__nuAhumCmim]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__uidx3, {
              [sty.svgstars_five__uidx3O4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__uidx3AWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__uidx3Oy01K]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__uidx3GjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__uidx3CGaiC]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__uidx3MCmim]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___2T0C, {
              [sty.svgstars_five___2T0CO4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four___2T0CaWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one___2T0Coy01K]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three___2T0CGjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two___2T0CcGaiC]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero___2T0CMCmim]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__etiz8, {
              [sty.svgstars_five__etiz8O4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__etiz8AWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one__etiz8Oy01K]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three__etiz8GjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__etiz8CGaiC]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero__etiz8MCmim]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg___0Ktgi, {
              [sty.svgstars_five___0KtgiO4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four___0KtgiaWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_one___0Ktgioy01K]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svgstars_three___0KtgiGjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two___0KtgicGaiC]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svgstars_zero___0KtgiMCmim]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__sMc8I, {
              [sty.svgstars_five__sMc8Io4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__sMc8IaWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__sMc8IgjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svgstars_two__sMc8IcGaiC]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__yncxy, {
              [sty.svgstars_five__yncxyo4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__yncxYaWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svgstars_three__yncxygjWi5]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__sosK9, {
              [sty.svgstars_five__sosK9O4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svgstars_four__sosK9AWa1Y]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(projectcss.all, sty.svg__jpe3D, {
              [sty.svgstars_five__jpe3DO4U7V]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRatings__ArgProps,
          internalVariantPropNames: PlasmicRatings__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
