// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJmo2tdG6kQGZ4iwYBrjeU
// Component: c5yLa0rKRkXDrk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header3 from "../../Header3"; // plasmic-import: 9fASFiAt8NFNyT/component
import Header2 from "../../Header2"; // plasmic-import: J4lJf__ulg_AyS/component
import ProductCard from "../../ProductCard"; // plasmic-import: BSQ6AFlYL_eYT0/component
import Ratings from "../../Ratings"; // plasmic-import: 6Seh2opbHxlH6n/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: UfFtit0F9KMo8Y/component
import BlogPost from "../../BlogPost"; // plasmic-import: 6G96xi_1i6SBB7/component
import Footer from "../../Footer"; // plasmic-import: f0WP3Kg2Vjqhf/component
import ProductRow from "../../ProductRow"; // plasmic-import: _lynD2Lh2S0A1Y/component
import { useScreenVariants as useScreenVariantsmSPqrdrCRlH2Q } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: mSPqrdrCRlH2Q-/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: bJmo2tdG6kQGZ4iwYBrjeU/projectcss
import sty from "./PlasmicSinglePage.module.css"; // plasmic-import: c5yLa0rKRkXDrk/css
import LeftArrowSvgrepoComsvgIcon from "./icons/PlasmicIcon__LeftArrowSvgrepoComsvg"; // plasmic-import: Fq3vVSHI2LWVG_/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: rHrabkGVopUVsx/icon
import header5JpgJpXDvH9LMi8ODm from "./images/header5Jpg.jpeg"; // plasmic-import: JpXDvH9LMi8oDM/picture
import plant6LgwebpGmmk7BcM0Hx9U from "./images/plant6Lgwebp.webp"; // plasmic-import: GMMK_7BcM0Hx9u/picture
import galinaNMiziNqvJx5MUnsplashjpgKq8Mxv2UfJtYIz from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpeg"; // plasmic-import: Kq8MXV2ufJtYIz/picture
import igorSonFvPxCqgtwcUnsplashjpgJaQzEvqCnmGg0K from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpeg"; // plasmic-import: JaQZEvqCnmGG0K/picture
import scottWebbORwRlTgBrPoUnsplashjpgEOgI7Ub5FNr00 from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpeg"; // plasmic-import: eOgI7UB5FNr00-/picture
import freddieMarriageUcfKyTanLuUnsplashjpgQo52Jm57Gl1YoF from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpeg"; // plasmic-import: QO52Jm57GL1YoF/picture
import f2LpYf5MQhAzaV from "./images/f2.jpeg"; // plasmic-import: LPYf5MQhAza-V_/picture
import f3Yvnqn5PMYvnt5M from "./images/f3.jpeg"; // plasmic-import: yvnqn5pMYvnt5M/picture
import f4TyA58LWa7L2Yrv from "./images/f4.jpeg"; // plasmic-import: tyA58lWA7L2YRV/picture
import b1NsD3CntDlfKy5 from "./images/b1.jpeg"; // plasmic-import: Ns-D3cntDlfKY5/picture
import b2Jw64HwElivnsy1 from "./images/b2.jpeg"; // plasmic-import: JW64hwElivnsy1/picture
import b35R9QudvmNo2E8M from "./images/b3.jpeg"; // plasmic-import: 5r9qudvmNO2E8M/picture
import adidasCCrvhQGfb8HRe9 from "./images/adidas.png"; // plasmic-import: cCrvhQGfb8HRe9/picture
import hm0FJWwM0P935Q5 from "./images/hm.png"; // plasmic-import: 0fJWwM0P935q-5/picture
import kappaBNhe0LiQxjWqxw from "./images/kappa.png"; // plasmic-import: bNHE0LiQxjWqxw/picture
import lacosteD18LkuZb25OP from "./images/lacoste.png"; // plasmic-import: D18lkuZb25_O-p/picture
import levisDmQcAw3XWoWmE from "./images/levis.png"; // plasmic-import: Dm-QcAW3xWOWmE/picture
import plant6JpgSmlpt5YHy4NcBw from "./images/plant6Jpg.png"; // plasmic-import: SMLPT5yHy4ncBw/picture
import plant1JpgVkPelBbfgDWkb from "./images/plant1Jpg.png"; // plasmic-import: Vk-PelBbfgDWkb/picture
import plant7JpgX0MLq28SL3ZZq from "./images/plant7Jpg.png"; // plasmic-import: X0MLq28S_L3ZZq/picture
import plant5Jpg0H04FmanF8FAzT from "./images/plant5Jpg.png"; // plasmic-import: 0H04fmanF8FAzT/picture
import plant41JpgEOuh2W04GMhb0R from "./images/plant41Jpg.png"; // plasmic-import: eOUH2W04gMHB0r/picture
import plant31JpgEpRe6YzR5Bmvfv from "./images/plant31Jpg.png"; // plasmic-import: epRe6yzR5Bmvfv/picture
import plant9WebpPhh9GvHcBSh8Se from "./images/plant9Webp.webp"; // plasmic-import: Phh9GvHcBSh8SE/picture
import plant2WebpDlXcs2SQpKtlju from "./images/plant2Webp.webp"; // plasmic-import: dlXcs2sQpKtlju/picture

export const PlasmicSinglePage__VariantProps = new Array();

export const PlasmicSinglePage__ArgProps = new Array();

function PlasmicSinglePage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsmSPqrdrCRlH2Q()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__yOCgw)}>
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__yy74)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobile") ? true : true
                  ) ? (
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___1Wu9E)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"35%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: header5JpgJpXDvH9LMi8ODm,
                        fullWidth: 502,
                        fullHeight: 872,
                        aspectRatio: undefined
                      }}
                    />
                  ) : null}

                  <Header3
                    data-plasmic-name={"header3"}
                    data-plasmic-override={overrides.header3}
                    className={classNames("__wab_instance", sty.header3)}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___3VOKd)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <p.Stack
                        as={"a"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__c2Jpx
                        )}
                      >
                        <LeftArrowSvgrepoComsvgIcon
                          className={classNames(projectcss.all, sty.svg__isjsn)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__t4MLa
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "see all products"
                            : "see all products"}
                        </div>
                      </p.Stack>
                    ) : null}

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground2"}
                      data-plasmic-override={overrides.foreground2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground2)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.columns__tc7FA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___8Mer1
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__eeiU7)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: plant6LgwebpGmmk7BcM0Hx9U,
                              fullWidth: 900,
                              fullHeight: 900,
                              aspectRatio: undefined
                            }}
                          />
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.column__muCgM
                          )}
                        >
                          <h3
                            data-plasmic-name={"h3"}
                            data-plasmic-override={overrides.h3}
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3
                            )}
                          >
                            {"Donec finibus"}
                          </h3>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fBt85
                            )}
                          >
                            {"big plants"}
                          </div>

                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5___9Dahu
                            )}
                          >
                            {"$100.00"}
                          </h5>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___85YVx
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__iCMwl
                              )}
                            >
                              {"Cras molestie faucibus ipsum ut vulputate."}
                            </div>

                            {(
                              hasVariant(globalVariants, "screen", "mobile")
                                ? true
                                : true
                            ) ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__cqhM
                                )}
                              >
                                {(
                                  hasVariant(globalVariants, "screen", "mobile")
                                    ? true
                                    : true
                                ) ? (
                                  <p.Stack
                                    as={"a"}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.a,
                                      sty.link__bYyP
                                    )}
                                  >
                                    <Icon3Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg___4Brg7
                                      )}
                                      role={"img"}
                                    />

                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___4OKAu
                                      )}
                                    >
                                      {hasVariant(
                                        globalVariants,
                                        "screen",
                                        "mobile"
                                      )
                                        ? "Discover"
                                        : "Add to cart"}
                                    </div>
                                  </p.Stack>
                                ) : null}
                              </div>
                            ) : null}
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </div>
                </div>
              ) : null}
            </div>
          ) : null}
          {true ? (
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wN91W)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___2Gxxd)}
                >
                  {true ? (
                    <Header2
                      data-plasmic-name={"header2"}
                      data-plasmic-override={overrides.header2}
                      className={classNames("__wab_instance", sty.header2)}
                    />
                  ) : null}
                </div>
              </p.Stack>

              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__gmN59)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___8HZru
                    )}
                  >
                    {"Top Collections"}
                  </h2>
                </div>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__ildF5)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__xbxCp)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__f5JI
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__eFgaD)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: galinaNMiziNqvJx5MUnsplashjpgKq8Mxv2UfJtYIz,
                            fullWidth: 1920,
                            fullHeight: 1278,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      onSale={true}
                      price={"$65.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__pr9Yo
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__vArbm)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__yplql
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__fdZUy)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: igorSonFvPxCqgtwcUnsplashjpgJaQzEvqCnmGg0K,
                            fullWidth: 640,
                            fullHeight: 481,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      onSale={true}
                      price={"$80.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__prTIk
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__qrRnG)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__rGoXv
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__mbfBn)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: scottWebbORwRlTgBrPoUnsplashjpgEOgI7Ub5FNr00,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$40.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings___4UeQ
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__tyPsW)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__koKgg
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__gTtWh)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: freddieMarriageUcfKyTanLuUnsplashjpgQo52Jm57Gl1YoF,
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      onSale={true}
                      price={"$100.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__hh4Gn
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>
                </p.Stack>
              ) : null}
              {true ? (
                <FeatureItem
                  data-plasmic-name={"featureItem"}
                  data-plasmic-override={overrides.featureItem}
                  className={classNames("__wab_instance", sty.featureItem)}
                />
              ) : null}
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__lmB8)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p2KV
                    )}
                  >
                    {"Featured Products"}
                  </div>
                </div>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__zfDjo)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__kxk2D)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__syuOx
                      )}
                      price={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zDohL
                          )}
                        >
                          {"$160.00"}
                        </div>
                      }
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__lVxMd
                          )}
                          numReviews={"(12 Review)"}
                          stars={"two"}
                        />
                      }
                      title={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2Mbtf
                          )}
                        >
                          {"Designed Sofa"}
                        </div>
                      }
                      withReviews={true}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__yd3Pp)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__cSx5A
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___13B06)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: f2LpYf5MQhAzaV,
                            fullWidth: 270,
                            fullHeight: 310,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$200.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__z1LgN
                          )}
                          stars={"four"}
                        />
                      }
                      title={"Dining Table"}
                      withReviews={true}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___6SC5A)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__bJlmZ
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__byunt)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: f3Yvnqn5PMYvnt5M,
                            fullWidth: 270,
                            fullHeight: 310,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$100.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__fOaba
                          )}
                          numReviews={"(23 Review)"}
                          stars={"five"}
                        />
                      }
                      title={"Chair and Table"}
                      withReviews={true}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__brulp)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__jiO5
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__zwP6)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: f4TyA58LWa7L2Yrv,
                            fullWidth: 270,
                            fullHeight: 310,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$299.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__ojKyd
                          )}
                          numReviews={"(35 Review)"}
                        />
                      }
                      title={"Modern Arm Chair"}
                      withReviews={true}
                    />
                  </div>
                </p.Stack>
              ) : null}
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__gh902)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e0JSy
                    )}
                  >
                    {"Latest Blog"}
                  </div>
                </div>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__ivDz)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__n8HdZ)}
                  >
                    <BlogPost
                      className={classNames(
                        "__wab_instance",
                        sty.blogPost__l9XOd
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__x9Unv)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: b1NsD3CntDlfKy5,
                            fullWidth: 370,
                            fullHeight: 250,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__ptzHu)}
                  >
                    <BlogPost
                      className={classNames(
                        "__wab_instance",
                        sty.blogPost__n6EVv
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__brm5S)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: b2Jw64HwElivnsy1,
                            fullWidth: 370,
                            fullHeight: 250,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__k12Nr)}
                  >
                    <BlogPost
                      className={classNames(
                        "__wab_instance",
                        sty.blogPost__cLs
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ckgOs)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: b35R9QudvmNo2E8M,
                            fullWidth: 370,
                            fullHeight: 250,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />
                  </div>
                </p.Stack>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__crRrv)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zlXba)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"90px"}
                    src={{
                      src: adidasCCrvhQGfb8HRe9,
                      fullWidth: 90,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yqDlV)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"91px"}
                    src={{
                      src: hm0FJWwM0P935Q5,
                      fullWidth: 91,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__q5GHb)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"98px"}
                    src={{
                      src: kappaBNhe0LiQxjWqxw,
                      fullWidth: 98,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nGDmp)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"124px"}
                    src={{
                      src: lacosteD18LkuZb25OP,
                      fullWidth: 124,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__hbGjK)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"125px"}
                    src={{
                      src: levisDmQcAw3XWoWmE,
                      fullWidth: 125,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />
                </p.Stack>
              ) : null}
              {true ? (
                <Footer
                  className={classNames("__wab_instance", sty.footer__cok1Q)}
                />
              ) : null}
            </div>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"bigPlants"}
              data-plasmic-override={overrides.bigPlants}
              hasGap={true}
              className={classNames(projectcss.all, sty.bigPlants)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hIuo)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___6BeSt
                    )}
                  >
                    {"Big plants"}
                  </h2>
                </p.Stack>
              ) : null}

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__gzGcv)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__bPgUs)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wdY3X)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant6JpgSmlpt5YHy4NcBw,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sK9Qs)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__n9ZH)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__nIa0B)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__qt1K
                      )}
                    >
                      {"Donec finibus"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xrsrC
                      )}
                    >
                      {"bigplants"}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__zpBEv
                      )}
                    >
                      {"$100.00"}
                    </h5>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__v7Q8O)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__s8E2C)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant1JpgVkPelBbfgDWkb,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__s2Ljk)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__msaK)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__qudnh)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mKuG0
                      )}
                    >
                      {"Nulla suscipit"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__v5Nn4
                      )}
                    >
                      {"bigplants "}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___0Ysvv
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__yqXy1)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__pLqTh)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant7JpgX0MLq28SL3ZZq,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8UBxP
                      )}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__lvsQn)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__zHbb4)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__iTj7P
                      )}
                    >
                      {"Sed consectetur"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3HOzw
                      )}
                    >
                      {"bigplants "}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__srKy6
                      )}
                    >
                      {"$18.40 "}
                    </h5>
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__plt2)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant5Jpg0H04FmanF8FAzT,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hHb94)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__fvoIu)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__knB5F)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__cpJGf
                      )}
                    >
                      {"Vestibulum eget"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y7Kp
                      )}
                    >
                      {"bigplants "}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__zgHex
                      )}
                    >
                      {"$220.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"cactuses"}
              data-plasmic-override={overrides.cactuses}
              hasGap={true}
              className={classNames(projectcss.all, sty.cactuses)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gIdpL)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__k2X9
                    )}
                  >
                    {"Cactuses"}
                  </h2>
                </p.Stack>
              ) : null}

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__erRu)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__zj0Yg)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___6Azkl)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant41JpgEOuh2W04GMhb0R,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zKi4)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__eEoj0)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__yTwR9)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__fPnJr
                      )}
                    >
                      {"Cras molestie"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h4BLj
                      )}
                    >
                      {"cactuses "}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__rtapB
                      )}
                    >
                      {"$24.99"}
                    </h5>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__nprLl)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___69Q5T)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant31JpgEpRe6YzR5Bmvfv,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jyB5)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__q4Us9)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__zchNs)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mfx5L
                      )}
                    >
                      {"Curabitur eu tempor"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vv24M
                      )}
                    >
                      {"Cactuses"}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__lv8Bd
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__xJ8Z2)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__picpk)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant9WebpPhh9GvHcBSh8Se,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rjmnX)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__ggRi)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ndRup)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__yDow3
                      )}
                    >
                      {"Fusce sagittis"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__efhHw
                      )}
                    >
                      {"Fusce sagittis"}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__zxHc
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__td0Qb)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cpLIy)}
                    displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant2WebpDlXcs2SQpKtlju,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ppZYf)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__xUiU)}
                        role={"img"}
                      />
                    </div>
                  ) : null}

                  <div
                    className={classNames(projectcss.all, sty.freeBox__htIdm)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__kPxHs
                      )}
                    >
                      {"Integer porta"}
                    </a>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a6U7P
                      )}
                    >
                      {"Cactuses"}
                    </div>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__aEcM7
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}

          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__acN)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__hkQlU
                  )}
                >
                  {"Related"}
                </h2>
              </p.Stack>
            ) : null}
            {(hasVariant(globalVariants, "screen", "mobile") ? true : true) ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>

          <Footer className={classNames("__wab_instance", sty.footer__iw3U6)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header3",
    "foreground2",
    "h3",
    "header",
    "header2",
    "featureItem",
    "bigPlants",
    "cactuses",
    "bestSellers",
    "productRow"
  ],

  header3: ["header3"],
  foreground2: ["foreground2", "h3"],
  h3: ["h3"],
  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSinglePage__ArgProps,
          internalVariantPropNames: PlasmicSinglePage__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicSinglePage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSinglePage";
  } else {
    func.displayName = `PlasmicSinglePage.${nodeName}`;
  }
  return func;
}

export const PlasmicSinglePage = Object.assign(
  // Top-level PlasmicSinglePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header3: makeNodeComponent("header3"),
    foreground2: makeNodeComponent("foreground2"),
    h3: makeNodeComponent("h3"),
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    // Metadata about props expected for PlasmicSinglePage
    internalVariantProps: PlasmicSinglePage__VariantProps,
    internalArgProps: PlasmicSinglePage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSinglePage;
/* prettier-ignore-end */
