// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJmo2tdG6kQGZ4iwYBrjeU
// Component: ACsxTXhP-u-EE
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: wqXBpLChZ1mUR/component
import Button from "../../Button"; // plasmic-import: IHFKkmwx8NvkPc/component
import ProductCard from "../../ProductCard"; // plasmic-import: BSQ6AFlYL_eYT0/component
import Ratings from "../../Ratings"; // plasmic-import: 6Seh2opbHxlH6n/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: UfFtit0F9KMo8Y/component
import BlogPost from "../../BlogPost"; // plasmic-import: 6G96xi_1i6SBB7/component
import Footer from "../../Footer"; // plasmic-import: f0WP3Kg2Vjqhf/component
import ProductRow from "../../ProductRow"; // plasmic-import: _lynD2Lh2S0A1Y/component
import { useScreenVariants as useScreenVariantsmSPqrdrCRlH2Q } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: mSPqrdrCRlH2Q-/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: bJmo2tdG6kQGZ4iwYBrjeU/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: ACsxTXhP-u-EE/css
import ButtonArrowIcon from "./icons/PlasmicIcon__ButtonArrow"; // plasmic-import: xzU3U0X9EM48hf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: tDU3oesTdReL6D/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: rHrabkGVopUVsx/icon
import QuotessvgIcon from "./icons/PlasmicIcon__Quotessvg"; // plasmic-import: Hdu7SszM4pSXr2/icon
import galinaNMiziNqvJx5MUnsplashjpgKq8Mxv2UfJtYIz from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpeg"; // plasmic-import: Kq8MXV2ufJtYIz/picture
import igorSonFvPxCqgtwcUnsplashjpgJaQzEvqCnmGg0K from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpeg"; // plasmic-import: JaQZEvqCnmGG0K/picture
import scottWebbORwRlTgBrPoUnsplashjpgEOgI7Ub5FNr00 from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpeg"; // plasmic-import: eOgI7UB5FNr00-/picture
import freddieMarriageUcfKyTanLuUnsplashjpgQo52Jm57Gl1YoF from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpeg"; // plasmic-import: QO52Jm57GL1YoF/picture
import f2LpYf5MQhAzaV from "./images/f2.jpeg"; // plasmic-import: LPYf5MQhAza-V_/picture
import f3Yvnqn5PMYvnt5M from "./images/f3.jpeg"; // plasmic-import: yvnqn5pMYvnt5M/picture
import f4TyA58LWa7L2Yrv from "./images/f4.jpeg"; // plasmic-import: tyA58lWA7L2YRV/picture
import b1NsD3CntDlfKy5 from "./images/b1.jpeg"; // plasmic-import: Ns-D3cntDlfKY5/picture
import b2Jw64HwElivnsy1 from "./images/b2.jpeg"; // plasmic-import: JW64hwElivnsy1/picture
import b35R9QudvmNo2E8M from "./images/b3.jpeg"; // plasmic-import: 5r9qudvmNO2E8M/picture
import adidasCCrvhQGfb8HRe9 from "./images/adidas.png"; // plasmic-import: cCrvhQGfb8HRe9/picture
import hm0FJWwM0P935Q5 from "./images/hm.png"; // plasmic-import: 0fJWwM0P935q-5/picture
import kappaBNhe0LiQxjWqxw from "./images/kappa.png"; // plasmic-import: bNHE0LiQxjWqxw/picture
import lacosteD18LkuZb25OP from "./images/lacoste.png"; // plasmic-import: D18lkuZb25_O-p/picture
import levisDmQcAw3XWoWmE from "./images/levis.png"; // plasmic-import: Dm-QcAW3xWOWmE/picture
import plant6JpgSmlpt5YHy4NcBw from "./images/plant6Jpg.png"; // plasmic-import: SMLPT5yHy4ncBw/picture
import plant1JpgVkPelBbfgDWkb from "./images/plant1Jpg.png"; // plasmic-import: Vk-PelBbfgDWkb/picture
import plant7JpgX0MLq28SL3ZZq from "./images/plant7Jpg.png"; // plasmic-import: X0MLq28S_L3ZZq/picture
import plant5Jpg0H04FmanF8FAzT from "./images/plant5Jpg.png"; // plasmic-import: 0H04fmanF8FAzT/picture
import plant41JpgEOuh2W04GMhb0R from "./images/plant41Jpg.png"; // plasmic-import: eOUH2W04gMHB0r/picture
import plant31JpgEpRe6YzR5Bmvfv from "./images/plant31Jpg.png"; // plasmic-import: epRe6yzR5Bmvfv/picture
import plant9WebpPhh9GvHcBSh8Se from "./images/plant9Webp.webp"; // plasmic-import: Phh9GvHcBSh8SE/picture
import plant2WebpDlXcs2SQpKtlju from "./images/plant2Webp.webp"; // plasmic-import: dlXcs2sQpKtlju/picture

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsmSPqrdrCRlH2Q()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__yj3HG)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__fhmjf)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__uoi0A)}>
                <Header
                  className={classNames("__wab_instance", sty.header__svsUg)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___9Wabu)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Real, beautiful plants \nright to your door"}
                  </h1>

                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kHuTv
                      )}
                    >
                      {"See all plants"}
                    </div>

                    <ButtonArrowIcon
                      className={classNames(projectcss.all, sty.svg___4Je)}
                      role={"img"}
                    />
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>

            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__fJkJf)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___1QKmA
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__lMziu)}
              >
                <div className={classNames(projectcss.all, sty.column__iinzR)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__bfeZt
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dVyVf)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: galinaNMiziNqvJx5MUnsplashjpgKq8Mxv2UfJtYIz,
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__ja6FL
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__g2M9S)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__b8K1X
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zwQgp)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: igorSonFvPxCqgtwcUnsplashjpgJaQzEvqCnmGg0K,
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__j2HhR
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__xO6Fd)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__pg6Ul
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dyrdK)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: scottWebbORwRlTgBrPoUnsplashjpgEOgI7Ub5FNr00,
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__rGd2N
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___4Ef0F)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__gzilX
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jsnai)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: freddieMarriageUcfKyTanLuUnsplashjpgQo52Jm57Gl1YoF,
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__akGo
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__vxXs)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__poDOo
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__cnxSk)}
              >
                <div className={classNames(projectcss.all, sty.column__fToty)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard___8XVvr
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ap8FT
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___9WwXf
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two"}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cuAMc
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__b65Gh)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__qixJ2
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___5PgxG)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f2LpYf5MQhAzaV,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__kmFFe
                        )}
                        stars={"four"}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__laf1J)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__dwf3R
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ylAbn)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f3Yvnqn5PMYvnt5M,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__dXzWp
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five"}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__vgD5F)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__prcl2
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__eCitQ)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: f4TyA58LWa7L2Yrv,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__dx8T8
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__hBlV7)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__juZxI
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__yerEa)}
              >
                <div className={classNames(projectcss.all, sty.column__pf7Fk)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__mF7E6
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hxSTx)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b1NsD3CntDlfKy5,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___8Od9N)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost___4NqLn
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___2LNjp)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b2Jw64HwElivnsy1,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__q9V6E)}>
                  <BlogPost
                    className={classNames("__wab_instance", sty.blogPost__uG1O)}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__fDWz3)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: b35R9QudvmNo2E8M,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__fWPor)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wuwkm)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  src={{
                    src: adidasCCrvhQGfb8HRe9,
                    fullWidth: 90,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gj8Gc)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"91px"}
                  src={{
                    src: hm0FJWwM0P935Q5,
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mfz25)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"98px"}
                  src={{
                    src: kappaBNhe0LiQxjWqxw,
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fkoE)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"124px"}
                  src={{
                    src: lacosteD18LkuZb25OP,
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__sLf1G)}
                  displayHeight={"60px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"125px"}
                  src={{
                    src: levisDmQcAw3XWoWmE,
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__fkK52)}
              />
            ) : null}
          </div>

          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qMhtG)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__pR7L)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___2Yi4
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uDyRt)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__dpXp4
                  )}
                >
                  {"Big plants"}
                </h2>
              </p.Stack>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__csnEf)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___8XYwW)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__zzSs)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant6JpgSmlpt5YHy4NcBw,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__b03Q7)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__cRlX6)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__sskA7)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fcnVd
                    )}
                  >
                    {"Donec finibus"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__u8Da
                    )}
                  >
                    {"bigplants"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__xsHeg
                    )}
                  >
                    {"$100.00"}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__xdEaj)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hBlj8)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant1JpgVkPelBbfgDWkb,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hnNO)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg___0JdNe)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__d5QdG)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xaV7Z
                    )}
                  >
                    {"Nulla suscipit"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3MUHi
                    )}
                  >
                    {"bigplants "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__h1Qz5
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__v1Q8Y)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__d4A6M)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant7JpgX0MLq28SL3ZZq,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vNiy6)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__nPnyf)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__aML)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xjYyB
                    )}
                  >
                    {"Sed consectetur"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tdMto
                    )}
                  >
                    {"bigplants "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__gslCc
                    )}
                  >
                    {"$18.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__pUvA)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__z77U0)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant5Jpg0H04FmanF8FAzT,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__euXcz)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__wC4UB)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__wGqUe)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wkxwd
                    )}
                  >
                    {"Vestibulum eget"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kwdvg
                    )}
                  >
                    {"bigplants "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__lYug
                    )}
                  >
                    {"$220.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hmHBr)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__wjPwX
                  )}
                >
                  {"Cactuses"}
                </h2>
              </p.Stack>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__nvsAx)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__clG13)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__shZal)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant41JpgEOuh2W04GMhb0R,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__d7W9J)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__y5BVz)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__jXkR)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zQ9N
                    )}
                  >
                    {"Cras molestie"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t3JEh
                    )}
                  >
                    {"cactuses "}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__c5GC
                    )}
                  >
                    {"$24.99"}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__exPQh)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__eKwJc)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant31JpgEpRe6YzR5Bmvfv,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qhS1)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__yYbw0)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__koP4P)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__nzbQq
                    )}
                  >
                    {"Curabitur eu tempor"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t6Mhw
                    )}
                  >
                    {"Cactuses"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__q3RJh
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6Hn32)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fNgpv)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant9WebpPhh9GvHcBSh8Se,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iL5Nl)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__vvj6Z)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__eIdnW)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__nqn3
                    )}
                  >
                    {"Fusce sagittis"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e7MFa
                    )}
                  >
                    {"Cactuses"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__efCkV
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__gk0Cc)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__uZvnD)}
                  displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: plant2WebpDlXcs2SQpKtlju,
                    fullWidth: 400,
                    fullHeight: 400,
                    aspectRatio: undefined
                  }}
                />

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__taUkc)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__aCu8P)}
                      role={"img"}
                    />
                  </div>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__bi7U9)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__h00Ek
                    )}
                  >
                    {"Integer porta"}
                  </a>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mVAm4
                    )}
                  >
                    {"Cactuses"}
                  </div>

                  <h5
                    className={classNames(
                      projectcss.all,
                      projectcss.h5,
                      projectcss.__wab_text,
                      sty.h5__g92S
                    )}
                  >
                    {"$49.40 "}
                  </h5>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ba6FF)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__a8GTd
                  )}
                >
                  {"Testimonials"}
                </h2>
              </p.Stack>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__iL82C)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__lckQg)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__hVzfk)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w5BqC
                  )}
                >
                  {
                    "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                  }
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__trHjf)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__wveU5
                      )}
                    >
                      {"JOHN DOPE,"}
                    </h5>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__lOvsQ
                      )}
                    >
                      {" COLORADO, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__tUSpB)}
              >
                <QuotessvgIcon
                  className={classNames(projectcss.all, sty.svg__f4PuS)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Wv0N
                  )}
                >
                  {
                    "Well I'll be d*mned. These plants really ARE greener than any of my recruits."
                  }
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qx6D)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__suj6
                      )}
                    >
                      {"MAJOR PAYNE"}
                    </h5>

                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__ooVsU
                      )}
                    >
                      {", VA, USA"}
                    </h5>
                  </p.Stack>
                ) : null}
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer className={classNames("__wab_instance", sty.footer__r78K1)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "h1",
    "button",
    "featureItem",
    "bestSellers",
    "productRow",
    "bigPlants",
    "cactuses",
    "testimonials"
  ],

  h1: ["h1"],
  button: ["button"],
  featureItem: ["featureItem"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  testimonials: ["testimonials"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    button: makeNodeComponent("button"),
    featureItem: makeNodeComponent("featureItem"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    testimonials: makeNodeComponent("testimonials"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
