// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bJmo2tdG6kQGZ4iwYBrjeU
// Component: _lynD2Lh2S0A1Y
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsmSPqrdrCRlH2Q } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: mSPqrdrCRlH2Q-/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_planty.module.css"; // plasmic-import: bJmo2tdG6kQGZ4iwYBrjeU/projectcss
import sty from "./PlasmicProductRow.module.css"; // plasmic-import: _lynD2Lh2S0A1Y/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: rHrabkGVopUVsx/icon
import plant1FeaturedjpgFj7SdJExkdtsq from "./images/plant1Featuredjpg.png"; // plasmic-import: FJ7sd_jEXKDTSQ/picture
import plant2Featuredjpg164Ex7ReJOpU from "./images/plant2Featuredjpg.png"; // plasmic-import: 164Ex7re-jOp_U/picture
import plant5FeaturedjpgCcaQosEvphg39W from "./images/plant5Featuredjpg.png"; // plasmic-import: ccaQOSEvphg39W/picture
import plant9Featuredjpg4FiTmZRhJifW35 from "./images/plant9Featuredjpg.png"; // plasmic-import: 4fiTmZRhJifW35/picture

export const PlasmicProductRow__VariantProps = new Array();

export const PlasmicProductRow__ArgProps = new Array();

function PlasmicProductRow__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsmSPqrdrCRlH2Q()
  });

  return true ? (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column__nRYgV)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__feEf6)}
          displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant1FeaturedjpgFj7SdJExkdtsq,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox___2CXd8)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg__a0R9P)}
              role={"img"}
            />
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox__bR1Sl)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__bfFoD
            )}
          >
            {"Nulla suscipit "}
          </a>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__k0GUt
            )}
          >
            {"bigplants "}
          </div>

          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5__zeZk
            )}
          >
            {"$49.40 "}
          </h5>
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column__xJb0G)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__fs2F1)}
          displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant2Featuredjpg164Ex7ReJOpU,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__w0UMl)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg___3VwgH)}
              role={"img"}
            />
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox__kh43B)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__a19R
            )}
          >
            {"Integer porta"}
          </a>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__tfAeK
            )}
          >
            {"cactuses"}
          </div>

          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5__pyfSh
            )}
          >
            {"$99.00 "}
          </h5>
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column___86UZw)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__jow4P)}
          displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant5FeaturedjpgCcaQosEvphg39W,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox___2Qked)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg__wcWze)}
              role={"img"}
            />
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox__qBMpM)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__cjEgE
            )}
          >
            {"Vestibulum eget"}
          </a>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__k0WlT
            )}
          >
            {"bigplants "}
          </div>

          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5__drPcr
            )}
          >
            {"$220.00 "}
          </h5>
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.column___3G65R)}
      >
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img___0TxUn)}
          displayHeight={"270px /* plasmic-token: 7poH7v2BwN-d7b */"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          loading={"lazy"}
          src={{
            src: plant9Featuredjpg4FiTmZRhJifW35,
            fullWidth: 400,
            fullHeight: 400,
            aspectRatio: undefined
          }}
        />

        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox___6XYiT)}>
            <Icon3Icon
              className={classNames(projectcss.all, sty.svg__pUmzo)}
              role={"img"}
            />
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox__kFhOn)}>
          <a
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link__nk90R
            )}
          >
            {"Fusce sagittis"}
          </a>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__u97IZ
            )}
          >
            {"cactuses"}
          </div>

          <h5
            className={classNames(
              projectcss.all,
              projectcss.h5,
              projectcss.__wab_text,
              sty.h5__x78W
            )}
          >
            {"$400.40 "}
          </h5>
        </div>
      </p.Stack>
    </p.Stack>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProductRow__ArgProps,
          internalVariantPropNames: PlasmicProductRow__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicProductRow__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductRow";
  } else {
    func.displayName = `PlasmicProductRow.${nodeName}`;
  }
  return func;
}

export const PlasmicProductRow = Object.assign(
  // Top-level PlasmicProductRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicProductRow
    internalVariantProps: PlasmicProductRow__VariantProps,
    internalArgProps: PlasmicProductRow__ArgProps
  }
);

export default PlasmicProductRow;
/* prettier-ignore-end */
